### ISSUE TITLE
Hangs During Inference with `tensor-parallel-size=2` on `gemma-2-9b-it`

### ISSUE THREAD

**Issue by ccs96307** [snowflakedb/ArcticInference#40]
Hi, thank you for the great work! It's useful for my job!

I encountering an issue when running inference on `gemma-2-9b-it` with speculative decoding enabled and using the LSTM speculator. The system works fine when using single-GPU, but starts hanging after several requests when I switch to multi-GPU (`--tensor-parallel-size=2`).

With `--tensor-parallel-size=2`, after a few successful completions, suddenly the Draft acceptance rate would be `nan%`.

```
INFO 05-09 16:50:18 [loggers.py:87] Engine 000: Avg prompt throughput: 12.0 tokens/s, Avg generation throughput: 9.1 tokens/s, Running: 1 reqs, Waiting: 0 reqs, GPU KV cache usage: 0.5%, Prefix cache hit rate: 50.0%                       
INFO 05-09 16:50:18 [metrics.py:53] SpecDecoding metrics: Draft acceptance rate: 33.3%, Accepted: 46 tokens, Drafted: 138 tokens                                                                                                              
INFO 05-09 16:50:28 [loggers.py:87] Engine 000: Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Waiting: 0 reqs, GPU KV cache usage: 0.5%, Prefix cache hit rate: 50.0%                        
INFO 05-09 16:50:28 [metrics.py:53] SpecDecoding metrics: Draft acceptance rate: nan%, Accepted: 0 tokens, Drafted: 0 tokens        
``` 

Could this be due to incorrect tensor-parallel handling inside speculative decoding logic?

Any thoughts or guidance would be sincerely appreciated.

**Comment by sfc-gh-aqiao** [comment]
@ccs96307 thanks for the report. @sfc-gh-yewang is looking into it, other users have faced similar hangs.

Just FYI, the LSTM and MLP draft models will only work with one specific LLM. For example https://huggingface.co/Snowflake/Arctic-LSTM-Speculator-Llama-3.1-8B-Instruct will only work with Llama-3.1-8B-Instruct.

If you need draft models for other LLMs, we suggest training your own using our training pipelines over at https://github.com/snowflakedb/ArcticTraining/tree/main/projects/arctic_lstm_speculator. You'll need to copy and modify the recipes.

**Comment by ccs96307** [comment]
Hi @sfc-gh-yewang, thank you for looking into this, and thank you all for your amazing work!

I’ve successfully trained a custom speculator model for my own LLM using the Arctic training pipeline—it runs very fast, and I really appreciate the help and documentation you’ve provided.

Right now, I’m in the testing phase, but unfortunately the server frequently hangs during generation.

Looking forward to any updates or fixes. Thanks again! 🙏

**Comment by sfc-gh-yewang** [comment]
@ccs96307 very short term, could you try temperature=0? This is the config that does not trigger hangs on my end.

**Comment by sfc-gh-yewang** [comment]
@ccs96307 
We figured out the root cause. In vLLM, with temperature > 0 each worker may generate different results. And in our suffix + spec decoding logic sometimes the arctic speculator is triggered in one worker and not in another which causes hang.

The solution is quite simple: just set seed value explicitly in the vllm constructor. 

e.g. (offline)
llm = LLM(..., seed=0, ...)
e.g. (bash)
vllm serve ... --seed 0 ...

**Comment by ccs96307** [comment]
@sfc-gh-yewang 
Indeed, when I used only suffix decoding, the issue disappeared.

After explicitly setting the --seed argument as you suggested, I no longer encounter the hanging issue — everything runs smoothly now!

Thank you so much! You’ve truly saved my week.
Really appreciate your help and all the amazing work from your team!
